#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

#include "recover.h"

int recover(int argc, char **argv){

    // Milestone 1: validate usage
    if(validate_usage(argc,argv) != 0){
        return -1;
    }

    return 0;
}

int validate_usage(int argc, char **argv){
    char *error_message = 
    "Usage: ./nyufile disk <options>\n"
    "  -i                     Print the file system information.\n"
    "  -l                     List the root directory.\n"
    "  -r filename [-s sha1]  Recover a contiguous file.\n"
    "  -R filename -s sha1    Recover a possibly non-contiguous file.\n";

    if(argc < 2){
        printf("%s", error_message);
        return -1;
    }

    int disk_len = strlen(argv[1]);
    if (disk_len < 5 || strcmp(argv[1] + disk_len - 5, ".disk") != 0) {
        printf("%s", error_message);
        return -1;
    }
    int option;
    int i_flag = 0, l_flag = 0, r_flag = 0, R_flag = 0, s_flag = 0;
    char *filename = NULL;
    char *sha1 = NULL;

    optind = 2;

    // Set opterr to 0 to disable default error messages generated by getopt()
    opterr = 0;

    while ((option = getopt(argc, argv, "ilr:R:s:")) != -1) {
        switch(option){
            case 'i':
                printf("option i\n");
                i_flag = 1;
                break;          
            case 'l':
                printf("option l\n");
                l_flag = 1;
                break;
            case 'r':
                if(optarg == NULL){
                    printf("%s", error_message);
                    return -1;
                }
                r_flag = 1;
                filename = optarg;
                break;
            case 's':
                if(optarg == NULL){
                    printf("%s", error_message);
                    return -1;
                }
                s_flag = 1;
                sha1 = optarg;
                break;
            case 'R':
                if(optarg == NULL){
                    printf("%s", error_message);
                    return -1;
                }
                R_flag = 1;
                filename = optarg;
                break;
            default:
                printf("%s", error_message);
                return -1;
        }
    }

    if(i_flag){
        // Print the file system information.
        printf("i flag is on\n");
    }else if(l_flag){
        // Print List the root directory.
        printf("l flag is on\n");
    }else if(r_flag && !s_flag){
        // Recover a contiguous file without shal
        printf("Recover a contiguous file without shal\n");
    }else if(r_flag && s_flag){
        // Recover a contiguous file shal
        printf("Recover a contiguous file with shal\n");
    }else if(R_flag && s_flag){
        // Recover a possibly non-contiguous file.
        printf("Recover a possibly non-contiguous file.\n");
    }else if(R_flag && !s_flag){
        printf("%s", error_message);
        return -1;
    }

    return 0;
}
